services:
  - type: web
    name: web-task-planner-api
    runtime: docker
    plan: free
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: CLERK_ISSUER
        sync: false
      - key: CLERK_JWK_SET_URI
        sync: false
      - key: CLERK_AUTHORIZED_PARTIES
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
